end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
        - BLEU
        - METEOR
    display_formula:
      metric:
        - Edit_dist
        - CDM
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: ./demo_data/omnidocbench_demo/OmniDocBench_demo.json
    prediction:
      data_path: ./demo_data/end2end
    match_method: quick_match
    # filter: 
    #   language: english
