recogition_eval:
  metrics:
    - Edit_dist
    - CDM
    - BLEU
  dataset:
    dataset_name: omnidocbench_single_module_dataset
    ground_truth:
      data_path: ./demo_data/recognition/OmniDocBench_demo_formula.json
      data_key: latex
      category_filter: ['equation_isolated']
    prediction:
      data_key: pred
    category_type: formula